<?php
echo $this->partial('common/image-annotate', [
    'imageSrc' => $imageSrc,
    'annotations' => $annotations,
]);
?>

<?php if ($item && 'item' === $displayTitle): ?>
<h3><?php echo $item->link($item->displayTitle()); ?></h3>
<?php elseif ($media && 'media' === $displayTitle): ?>
<h3><?php echo $media->link($media->displayTitle()); ?></h3>
<?php endif; ?>

<?php if ($caption): ?>
<div class="caption"><?php echo $caption; ?></div>
<?php endif; ?>
